# my global config
global:
  scrape_interval: 15s
  external_labels:
    monitor: homelab-monitor
  evaluation_interval: 15s
rule_files: null
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 'localhost:9090'

# change to different values
remote_write:
  - url: "https://localhost:9090/api/v1/write"
    basic_auth:
      username: "admin"
      password: "password"
