basic_settings:
  site_title: Simples
  site_tagline: A super simple blogging theme for Jekyll.
  favicon_image: /images/favicon.png

header_settings:
  avatar_image: /images/avatar.jpg
  logo_image: 
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'Latest'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'About'
      url: '/about'
    - title: 'Contact'
      url: '/contact'

grid_settings:
  grid_spacing: 10

contact_settings:
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  accent_color: '#ee983d'
  border_color: '#f7d7b6'
  overlay_background_color: '#161B21'
  overlay_text_color: '#ffffff'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Nunito:300,400,400i,600" rel="stylesheet">'
  title_font: '"Nunito", sans-serif'
  body_font: '"Nunito", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 27
    medium_size: 32
    large_size: 40
    weight: 600
    letter_spacing: 0
  site_tagline:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 600
    letter_spacing: 0
  h1:
    small_size: 27
    medium_size: 38
    large_size: 50
    weight: 600
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 27
    medium_size: 38
    large_size: 50
    weight: 600
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 400
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 17
    medium_size: 19
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""